### ISSUE TITLE
GKE ingress

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/knowledge#136]
## 在 GCP 工程中安装 Internal Ingress 暴露 GKE 负载均衡器

以下是安装 Internal Ingress 暴露 GKE 负载均衡器的详细步骤和操作流程：

**一、准备工作**

1. 确保您已拥有一个 GCP 项目和一个 GKE 集群。
2. 安装 kubectl 命令行工具。
3. 确保您拥有 Kubernetes 集群的 kubeconfig 文件。

**二、安装 Internal Ingress 控制器**

1. 选择一个 Internal Ingress 控制器，例如 NGINX Ingress Controller 或 Istio Ingress Gateway。
2. 根据您选择的控制器，按照官方文档进行安装。

**三、创建 Ingress 资源**

1. 创建一个 Ingress 资源，定义您要暴露的 GKE 服务和域名。
2. 在 Ingress 资源中，指定以下内容：
    * `spec.rules`: 定义域名和路径规则。
    * `spec.backend`: 定义要暴露的 GKE 服务。
    * `annotations`: 添加必要的注释，例如 `kubernetes.io/ingress.class` 用于指定 Ingress 控制器。

**四、创建 Service 资源**

1. 创建一个 Service 资源，定义您要暴露的 GKE 服务。
2. 在 Service 资源中，指定以下内容：
    * `spec.type`: 指定服务类型，例如 `LoadBalancer` 或 `ClusterIP`。
    * `spec.selector`: 指定要暴露的 Pod 选择器。

**五、测试 Ingress**

1. 使用 `kubectl get ingress` 命令查看 Ingress 资源状态。
2. 使用 `curl` 命令测试 Ingress 访问。

**操作流程**

1. 安装 Internal Ingress 控制器。
2. 创建 Ingress 资源。
3. 创建 Service 资源。
4. 测试 Ingress。

**注意**

* 确保您已授予必要的权限，以便 Ingress 控制器可以访问 GKE 集群。
* 不同 Ingress 控制器可能需要不同的配置，请参考官方文档进行详细配置。

**参考文档**

* NGINX Ingress Controller: https://kubernetes.github.io/ingress-nginx/
* Istio Ingress Gateway: https://istio.io/latest/docs/tasks/traffic-management/ingress/

**示例**

以下是一个示例 Ingress 资源，用于暴露名为 `my-service` 的 GKE 服务：

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: my-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80
  annotations:
    kubernetes.io/ingress.class: nginx
```

请根据您的实际情况修改该示例。

Here is a step-by-step guide to installing an internal ingress in a GCP project to expose a load balancer in a GKE cluster:

**Step 1: Create a GKE cluster**

* Go to the Google Cloud Console and navigate to the Kubernetes Engine page
* Click on "Create a cluster" and follow the wizard to create a new GKE cluster
* Choose the desired cluster configuration, including the number of nodes, machine type, and networking options

**Step 2: Create a load balancer in GKE**

* Create a deployment and service in your GKE cluster that you want to expose through the internal ingress
* Create a load balancer service in your GKE cluster using the following command:
```
kubectl expose deployment <deployment-name> --type=LoadBalancer --name=<load-balancer-name>
```
* Verify that the load balancer is created and running using the following command:
```
kubectl get svc
```

**Step 3: Create a internal ingress resource**

* Create a YAML file for the internal ingress resource, for example:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: internal-ingress
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
spec:
  rules:
  - host: <internal-hostname>
    http:
      paths:
      - path: /*
        backend:
          serviceName: <load-balancer-name>
          servicePort: 80
```
* Apply the YAML file to create the internal ingress resource using the following command:
```
kubectl apply -f internal-ingress.yaml
```
* Verify that the internal ingress resource is created and running using the following command:
```
kubectl get ingress
```

**Step 4: Create a firewall rule to allow traffic to the internal ingress**

* Go to the Google Cloud Console and navigate to the VPC Network page
* Click on "Create a firewall rule" and follow the wizard to create a new firewall rule
* Choose the desired firewall rule configuration, including the network, protocol, and port range
* Add a target tag to the firewall rule to allow traffic to the internal ingress, for example:
```
targetTags: ["internal-ingress"]
```
* Verify that the firewall rule is created and running using the following command:
```
gcloud compute firewall-rules list
```

**Step 5: Configure the internal ingress to use the load balancer**

* Update the internal ingress resource to use the load balancer service, for example:
```
kubectl patch ingress internal-ingress -p='{"spec":{"rules":[{"host":"<internal-hostname>","http":{"paths":[{"path":"/","backend":{"serviceName":"<load-balancer-name>","servicePort":80}}]}}]}}'
```
* Verify that the internal ingress resource is updated and running using the following command:
```
kubectl get ingress
```

**Step 6: Test the internal ingress**

* Use a tool like `curl` or `wget` to test the internal ingress, for example:
```
curl http://<internal-hostname>
```
* Verify that the request is routed to the load balancer and the backend service is responding correctly

**Operation Flow:**

Here is a high-level overview of the operation flow:

1. Create a GKE cluster and deploy a load balancer service
2. Create an internal ingress resource to expose the load balancer service
3. Create a firewall rule to allow traffic to the internal ingress
4. Configure the internal ingress to use the load balancer service
5. Test the internal ingress to verify that it is working correctly

Note: This is a high-level guide and you may need to modify the steps and configurations based on your specific use case and requirements.
