### ISSUE TITLE
Top pod

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/knowledge#86]
在Google Kubernetes Engine (GKE) 中查看 Pod 的内存和 CPU 使用率可以通过不同的方式进行：

1. **通过 GKE 控制台**：
   - 登录到 Google Cloud Console 并导航到 GKE 控制台。
   - 选择相应的集群和命名空间。
   - 在 "工作负载" 部分，找到你关心的 Pod。
   - 单击 Pod 名称以打开 Pod 详情页面。
   - 在 "监控" 标签下，你可以查看内存和 CPU 使用率的图表。

2. **使用 kubectl**：
   - 打开终端并确保你有正确的 Kubernetes 上下文。
   - 运行以下命令查看 Pod 的资源使用情况：

     ```bash
     kubectl top pod <pod-name> --namespace=<namespace-name>
     ```

     请替换 `<pod-name>` 和 `<namespace-name>` 为你要查看的 Pod 名称和命名空间。

   - 这将显示 Pod 的 CPU 和内存使用率。

如果你想进一步自动化监控或集成这些数据，你还可以考虑使用 Prometheus 和 Grafana 这样的监控工具。这需要在集群中设置相应的监控解决方案。

**Comment by aibangjuxin** [comment]
在 Google Kubernetes Engine (GKE) 中，您可以使用不同的方式查看 Pod 的内存和 CPU 使用率。以下是两种常用的方法：

1. 使用 Kubernetes Dashboard：
   - 打开 GKE 控制台，并导航到您的集群。
   - 在左侧导航菜单中，选择 "Workloads"。
   - 在 "Workloads" 页面上，您将看到您的 Pod 列表。
   - 单击您感兴趣的 Pod 的名称，以打开该 Pod 的详细信息页面。
   - 在详细信息页面上，您可以查看该 Pod 的资源使用情况，包括内存和 CPU。

2. 使用 kubectl 命令行工具：
   - 打开终端或命令提示符，并确保已安装和配置了 kubectl 工具。
   - 使用以下命令获取集群中的 Pod 列表及其详细信息：
     ```
     kubectl get pods
     ```
   - 找到您感兴趣的 Pod 的名称，然后使用以下命令获取该 Pod 的资源使用情况：
     ```
     kubectl describe pod <pod-name>
     ```
     将 `<pod-name>` 替换为您要查看的 Pod 的实际名称。
   - 在输出中，您将看到与该 Pod 相关的资源使用情况，包括内存和 CPU。

这些方法可以帮助您在 GKE 中查看 Pod 的内存和 CPU 使用率。您可以根据自己的偏好和需求选择适合您的方式。

**Comment by aibangjuxin** [comment]
要查看请求与实际使用量之间的关系，你可以考虑使用 Kubernetes 中的 Horizontal Pod Autoscaler（HPA）。 HPA 允许你基于指标（如 CPU 使用率或自定义指标）自动调整 Pod 的副本数量，以应对负载变化。

以下是一些步骤和命令行示例：

1. **启用自动缩放**：
   - 在你的 Deployment 或 StatefulSet 的 YAML 文件中，添加或确保已经存在 `resources` 部分，以及你感兴趣的自动缩放指标，比如 CPU 使用率。

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: example-deployment
   spec:
     replicas: 3
     template:
       metadata:
         labels:
           app: example
       spec:
         containers:
         - name: example-container
           image: example-image
           resources:
             limits:
               cpu: 500m
             requests:
               cpu: 200m
   ```

2. **检查 HPA 状态**：
   - 使用以下命令检查 Horizontal Pod Autoscaler 的状态：

   ```bash
   kubectl get hpa
   ```

   这将显示与 HPA 相关的信息，包括当前副本数、目标值和实际值。

3. **观察缩放事件**：
   - 如果自动缩放发生，你可以通过查看事件来获取更多信息：

   ```bash
   kubectl describe hpa <hpa-name>
   ```

   替换 `<hpa-name>` 为你的 HPA 的名称。

这样，你就可以在请求量增加时自动调整 Pod 的副本数量，确保系统能够应对变化的负载。
